### ISSUE TITLE
3.1.2 segfaults on Linux

### ISSUE THREAD

**Issue by cassandracomar** [ichi-rika/speech-analysis#27]
running on nixos unstable. 3.1 and 3.0.3 both work but 3.1.2 crashes with a segfault as soon as it brings up the UI. might be that I need to provide some system font library that I'm not currently providing but I'm not getting any output that indicates what that might be:

```
InFormant-DF-3.1.2-Linux-x86_64.AppImage installed in /home/cassandra/.cache/appimage-run/d41f0991ca5cbea35f19db7731723966aec959d1c187d37694800a87767cdd23
[2021-07-22 10:39:22] Reading configuration from: "/home/cassandra/.config/informant.conf"
[2021-07-22 10:39:22] Audio::Resampler#0] Created 48000 --> 0
[2021-07-22 10:39:22] Audio::Resampler#1] Created 0 --> 0
[2021-07-22 10:39:23] Audio::Resampler#2] Created 0 --> 0
[2021-07-22 10:39:23] Audio::Resampler#3] Created 0 --> 0
[2021-07-22 10:39:23] Audio::Resampler#4] Created 0 --> 0
[2021-07-22 10:39:23] Audio::Resampler#5] Created 48000 --> 0
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
[2021-07-22 10:39:23] ALSA lib pcm.c:2731:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
[2021-07-22 10:39:23] ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
[2021-07-22 10:39:23] Audio::Buffer#0] Sample rate changed, might cause jank for the next few frames.
[2021-07-22 10:39:23] Audio::Queue] Not enough data to pull. Adjusted block duration to 50.25 ms
[2021-07-22 10:39:23] Audio::Queue] Not enough data to pull. Adjusted block duration to 50.5 ms
[2021-07-22 10:39:23] Audio::Queue] Not enough data to pull. Adjusted block duration to 50.75 ms
[2021-07-22 10:39:23] Audio::Queue] Not enough data to pull. Adjusted block duration to 51 ms
[2021-07-22 10:39:23] Audio::Queue] Not enough data to pull. Adjusted block duration to 51.25 ms
[2021-07-22 10:39:23] Audio::Queue] Not enough data to pull. Adjusted block duration to 51.5 ms
[2021-07-22 10:39:23] Audio::Queue] Not enough data to pull. Adjusted block duration to 51.75 ms
[2021-07-22 10:39:23] Audio::Queue] Not enough data to pull. Adjusted block duration to 52 ms
segmentation fault (core dumped)
```

**Comment by clo-yunhee** [comment]
Can you run the appimage with gdb?

**Comment by nekoknot** [comment]
I'm having the same issue. Here's the backtrace from gdb; unfortunately there are no debugging symbols.

```(gdb) bt
#0  0x0000555555614628 in ?? ()
#1  0x0000555555614dd3 in ?? ()
#2  0x00005555556172d2 in ?? ()
#3  0x00005555556175c4 in ?? ()
#4  0x000055555561536e in ?? ()
#5  0x00007ffff6f2dcc1 in QQuickFramebufferObject::updatePaintNode(QSGNode*, QQuickItem::UpdatePaintNodeData*) () from /tmp/.mount_InForm9pIjHI/usr/bin/../lib/libQt6Quick.so.6
#6  0x00007ffff6dc3ce0 in QQuickWindowPrivate::updateDirtyNode(QQuickItem*) () from /tmp/.mount_InForm9pIjHI/usr/bin/../lib/libQt6Quick.so.6
#7  0x00007ffff6dc452b in QQuickWindowPrivate::updateDirtyNodes() () from /tmp/.mount_InForm9pIjHI/usr/bin/../lib/libQt6Quick.so.6
#8  0x00007ffff6dc5d25 in QQuickWindowPrivate::syncSceneGraph() () from /tmp/.mount_InForm9pIjHI/usr/bin/../lib/libQt6Quick.so.6
#9  0x00007ffff6f35ef8 in ?? () from /tmp/.mount_InForm9pIjHI/usr/bin/../lib/libQt6Quick.so.6
#10 0x00007ffff6f37e6f in ?? () from /tmp/.mount_InForm9pIjHI/usr/bin/../lib/libQt6Quick.so.6
#11 0x00007ffff6f38c86 in ?? () from /tmp/.mount_InForm9pIjHI/usr/bin/../lib/libQt6Quick.so.6
#12 0x00007ffff59759d5 in ?? () from /tmp/.mount_InForm9pIjHI/usr/bin/../lib/libQt6Core.so.6
#13 0x00007ffff78aa259 in start_thread () from /usr/lib/libpthread.so.0
#14 0x00007ffff54565e3 in clone () from /usr/lib/libc.so.6```

**Comment by nekoknot** [comment]
I built it myself using the docker method, and it works "fine". It actually starts, unlike the given binaries, but it segfaults on close.

For starters, https://github.com/clo-yunhee/in-formant/blob/0390c3ad33da53addcefa7afdbd2833651f6dc4a/docker/Dockerfile.linux#L1 is missing an `F`

This makes packaging the build fail if you don't build as a user with write permission to `/`
https://github.com/clo-yunhee/in-formant/blob/0390c3ad33da53addcefa7afdbd2833651f6dc4a/docker/deploy-linux.sh#L5

And the instructions should probably mention running `git submodule update --init` cause I didn't realize I needed to do it.


Anyway, as I said, it starts up fine but segfaults when closing. Here's what it dumps:

```[2021-08-27 18:15:35] Reading configuration from: "/tmp/tmp/config/informant.conf"
[2021-08-27 18:15:35] Config not found, using defaults...
[2021-08-27 18:15:35] Audio::Resampler#0] Created 48000 --> 0
[2021-08-27 18:15:35] Audio::Resampler#1] Created 0 --> 0
[2021-08-27 18:15:35] Audio::Resampler#2] Created 0 --> 0
[2021-08-27 18:15:35] Audio::Resampler#3] Created 0 --> 0
[2021-08-27 18:15:35] Audio::Resampler#4] Created 48000 --> 0
[2021-08-27 18:15:35] ALSA lib pcm_dsnoop.c:600:(snd_pcm_dsnoop_open) unable to open slave
[2021-08-27 18:15:35] ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
[2021-08-27 18:15:35] ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
[2021-08-27 18:15:35] ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
[2021-08-27 18:15:35] ALSA lib pcm.c:2660:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
[2021-08-27 18:15:35] Cannot connect to server socket err = No such file or directory
[2021-08-27 18:15:35] Cannot connect to server request channel
[2021-08-27 18:15:35] jack server is not running or cannot be started
[2021-08-27 18:15:35] JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[2021-08-27 18:15:35] JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[2021-08-27 18:15:35] Cannot connect to server socket err = No such file or directory
[2021-08-27 18:15:35] Cannot connect to server request channel
[2021-08-27 18:15:35] jack server is not running or cannot be started
[2021-08-27 18:15:35] JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[2021-08-27 18:15:35] JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[2021-08-27 18:15:35] ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
[2021-08-27 18:15:35] ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
[2021-08-27 18:15:35] ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
[2021-08-27 18:15:35] ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
[2021-08-27 18:15:35] ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
[2021-08-27 18:15:35] ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
[2021-08-27 18:15:35] ALSA lib pcm_dmix.c:1035:(snd_pcm_dmix_open) unable to open slave
[2021-08-27 18:15:35] Audio::Buffer#0] Sample rate changed, might cause jank for the next few frames.
[2021-08-27 18:15:40] Audio::Queue] Not enough data to pull. Adjusted block duration to 50.25 ms
[2021-08-27 18:15:40] Audio::Queue] Not enough data to pull. Adjusted block duration to 50.5 ms
[2021-08-27 18:15:40] Audio::Queue] Not enough data to pull. Adjusted block duration to 50.75 ms
[2021-08-27 18:15:40] Audio::Queue] Not enough data to pull. Adjusted block duration to 51 ms
[2021-08-27 18:15:40] Audio::Queue] Not enough data to pull. Adjusted block duration to 51.25 ms
[2021-08-27 18:15:41] Audio::Queue] Not enough data to pull. Adjusted block duration to 51.5 ms
[2021-08-27 18:15:41] Audio::Queue] Not enough data to pull. Adjusted block duration to 51.75 ms
[2021-08-27 18:15:41] Audio::Queue] Not enough data to pull. Adjusted block duration to 52 ms
[2021-08-27 18:15:41] /opt/Qt/6.1.2/gcc_64/include/QtCore/qrect.h:412:12: runtime error: signed integer overflow: -2147483648 + -2147483648 cannot be represented in type 'int'
[2021-08-27 18:15:41] Processing fast enough, adjusted block size to 384 samples
[2021-08-27 18:15:41] AddressSanitizer:DEADLYSIGNAL
[2021-08-27 18:15:42] =================================================================
[2021-08-27 18:15:42] ==3011516==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f00873158cc bp 0x000000000000 sp 0x7f0038ffca20 T18)
[2021-08-27 18:15:42] ==3011516==The signal is caused by a READ memory access.
[2021-08-27 18:15:42] ==3011516==Hint: address points to the zero page.
[2021-08-27 18:15:42]     #0 0x7f00873158cc in QThreadStorageData::get() const (/tmp/.mount_InForm6hkMjC/usr/bin/../lib/libQt6Core.so.6+0x2cc8cc)
[2021-08-27 18:15:42]     #1 0x7f0088382ae7 in QOpenGLContext::currentContext() (/tmp/.mount_InForm6hkMjC/usr/bin/../lib/libQt6Gui.so.6+0x4d6ae7)
[2021-08-27 18:15:42]     #2 0x7f008839e9e9  (/tmp/.mount_InForm6hkMjC/usr/bin/../lib/libQt6Gui.so.6+0x4f29e9)
[2021-08-27 18:15:42]     #3 0x7f0088c009da  (/tmp/.mount_InForm6hkMjC/usr/bin/../lib/libQt6Quick.so.6+0x3a59da)
[2021-08-27 18:15:42]     #4 0x7f0088c06f1e  (/tmp/.mount_InForm6hkMjC/usr/bin/../lib/libQt6Quick.so.6+0x3abf1e)
[2021-08-27 18:15:42]     #5 0x7f0088c02ad9  (/tmp/.mount_InForm6hkMjC/usr/bin/../lib/libQt6Quick.so.6+0x3a7ad9)
[2021-08-27 18:15:42]     #6 0x7f0088c02cda  (/tmp/.mount_InForm6hkMjC/usr/bin/../lib/libQt6Quick.so.6+0x3a7cda)
[2021-08-27 18:15:42]     #7 0x7f008730d9d4  (/tmp/.mount_InForm6hkMjC/usr/bin/../lib/libQt6Core.so.6+0x2c49d4)
[2021-08-27 18:15:42]     #8 0x7f0089583258 in start_thread (/usr/lib/libpthread.so.0+0x9258)
[2021-08-27 18:15:42]     #9 0x7f00864ab5e2 in __GI___clone (/usr/lib/libc.so.6+0xfe5e2)
[2021-08-27 18:15:42]
=================================================================
==3011541==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc5eca1c21 at pc 0x7f0089ed233a bp 0x7ffc5eca1b50 sp 0x7ffc5eca12f8
READ of size 13 at 0x7ffc5eca1c21 thread T0
    #0 0x7f0089ed2339  (/tmp/.mount_InForm6hkMjC/usr/bin/../lib/libasan.so.6+0x3f339)
    #1 0x5646805749bc  (/tmp/.mount_InForm6hkMjC/usr/bin/in-formant+0xf119bc)
    #2 0x5646805674a4 in main (/tmp/.mount_InForm6hkMjC/usr/bin/in-formant+0xf044a4)
    #3 0x7f00863d4b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
    #4 0x56468051762d in _start (/tmp/.mount_InForm6hkMjC/usr/bin/in-formant+0xeb462d)

Address 0x7ffc5eca1c21 is located in stack of thread T0 at offset 177 in frame
    #0 0x564680574481  (/tmp/.mount_InForm6hkMjC/usr/bin/in-formant+0xf11481)

  This frame has 4 object(s):
    [48, 56) 'pipefd' (line 46)
    [80, 112) 'filename' (line 36)
    [144, 177) 'rdbuf' (line 72) <== Memory access at offset 177 overflows this variable
    [224, 1248) 'linebuf' (line 68)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow (/tmp/.mount_InForm6hkMjC/usr/bin/../lib/libasan.so.6+0x3f339)
Shadow bytes around the buggy address:
  0x10000bd8c330: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000bd8c340: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000bd8c350: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000bd8c360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
  0x10000bd8c370: f1 f1 00 00 00 f2 f2 f2 00 00 00 00 f2 f2 f2 f2
=>0x10000bd8c380: 00 00 00 00[01]f2 f2 f2 f2 f2 00 00 00 00 00 00
  0x10000bd8c390: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000bd8c3a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000bd8c3b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000bd8c3c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10000bd8c3d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==3011541==ABORTING
```

gdb says this:
```Thread 18 "QSGRenderThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffddc3d640 (LWP 3013137)]
0x00007ffff4a698cc in QThreadStorageData::get() const () from /tmp/.mount_InFormMxHTWx/usr/bin/../lib/libQt6Core.so.6
(gdb) bt
#0  0x00007ffff4a698cc in QThreadStorageData::get() const () from /tmp/.mount_InFormMxHTWx/usr/bin/../lib/libQt6Core.so.6
#1  0x00007ffff5ad6ae8 in QOpenGLContext::currentContext() () from /tmp/.mount_InFormMxHTWx/usr/bin/../lib/libQt6Gui.so.6
#2  0x00007ffff5af29ea in ?? () from /tmp/.mount_InFormMxHTWx/usr/bin/../lib/libQt6Gui.so.6
#3  0x00007ffff63549db in ?? () from /tmp/.mount_InFormMxHTWx/usr/bin/../lib/libQt6Quick.so.6
#4  0x00007ffff635af1f in ?? () from /tmp/.mount_InFormMxHTWx/usr/bin/../lib/libQt6Quick.so.6
#5  0x00007ffff6356ada in ?? () from /tmp/.mount_InFormMxHTWx/usr/bin/../lib/libQt6Quick.so.6
#6  0x00007ffff6356cdb in ?? () from /tmp/.mount_InFormMxHTWx/usr/bin/../lib/libQt6Quick.so.6
#7  0x00007ffff4a619d5 in ?? () from /tmp/.mount_InFormMxHTWx/usr/bin/../lib/libQt6Core.so.6
#8  0x00007ffff6cd7259 in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007ffff3bff5e3 in clone () from /usr/lib/libc.so.6
```



But yeah, it starts up fine though, so I don't know what's going on with the provided 3.1.2 binary.
